### ISSUE TITLE
My Reports Graphs not working?

### ISSUE THREAD

**Issue by mrjohnpoz** [jullrich/ISC-Bugs#10]
Tried multiple browsers.  When you go to my reports section Grpahs just always say 

Waiting for data....

Graphs work on the dashboard page.  But not 
![nographs](https://cloud.githubusercontent.com/assets/11797687/20640364/7d87b56c-b3a1-11e6-8527-2322256febc3.png)

**Comment by jullrich** [comment]
should be working again. the graph can be slow to build at times.
