### ISSUE TITLE
Login not persistent

### ISSUE THREAD

**Issue by Monti22** [jullrich/ISC-Bugs#11]
Login to ISC, change page to dshield... login again, click information news.... login again, click +1 on a story...login again
It would appear that login is not persistent throughout site.

**Comment by jullrich** [comment]
can't appear to reproduce this. Will try to look at the logs. If you could let me know your userid/email address so I can check the logs.

**Comment by Monti22** [comment]
[*** edited for privacy ***]

**Comment by jullrich** [comment]
Thanks (edited your post above for privacy). Do you use any particular plugins? It looks like your browser (Firefox?) isn't sending your cookie along.In particular the cookie called "dshield" is required to maintain your session.

**Comment by Monti22** [comment]
I do .. Adblock+ and uBlock Origin running on Firefox.. not sure which one it was but after turning both off.. everything is working fine.. Sorry about that, I should have done that first..

**Comment by jullrich** [comment]
thanks. will see if we can improve our cookies to make it past these plugins (Adblock should be fine. never tried uBlock Origin)
