### ISSUE TITLE
Daily Stormcasts file name misses "ISCStormCast"

### ISSUE THREAD

**Issue by dhalber** [jullrich/ISC-Bugs#12]
Hello,
I noticed that for the past few days, Daily Stormcasts files, e.g., https://traffic.libsyn.com/securitypodcast/5283.mp3, miss the ISCStormCast part in their file name.
It used to be ISCStormCast5283.mp3, rather than the new 5283.mp3.
The "ISCStormCast" prefix was nice to sort among other podcast files; so if possible, I would appreciate it coming back.
Thanks
P.S.  And thank you for the podcast, obviously!

**Comment by jullrich** [comment]
hm. that may be difficult. Libsyn doesn't appear to have the ability to simply rename files that are already uploaded and "archived". I would have to upload the files again (which costs... not a lot ... but they charge based on the amount of data uploaded to their servers)

**Comment by dhalber** [comment]
Sorry, I was not clear.  My request is that FUTURE files start again with the prefix ISCStormCast.

**Comment by jullrich** [comment]
ok. will see what I can do. But I would rather keep them consistent. (well, I guess I broke that rule already)

**Comment by dhalber** [comment]
Thank you.
Two screenshots to clarify even further if necessary, and also please notice that on November 23, TWO entries were published: the regular one and the short one (leading to files without ISCStormCast prefix), and since then only short file names are published.
[Two RSS entries on Nov 23](https://i.imgur.com/DESdoi7.png)
[File names](https://i.imgur.com/9RoKYnf.png)

**Comment by jullrich** [comment]
closing this. This is sadly not "fixable" the way I wanted it to be fixed and the file names will continue to follow the new format. If it would help, I could setup a redirect. Open this issue again or start a new issue if this is something that will help.

**Comment by dhalber** [comment]
Thank you for having taken the time to respond before closing this issue.  
I quickly checked the last 1864 mp3 files for podcasts I listened to, and it appears that the only other podcast that produces pure-numerical sequences is a weekly podcast currently at 160, so not difficult to distinguish from 5429.mp3.  In a way, you're saved by the vast majority of your peers having their podcast name, and sometimes episode title, in the file name; on the other hand, your file metadata are stellar.
