### ISSUE TITLE
When using IP/domain lookup it refers me back to the login page even when I'm already logged in.

### ISSUE THREAD

**Issue by kmcvicker** [jullrich/ISC-Bugs#13]
I am logged in and try to use the IP lookup page.  When I search I am refered back to the login page. 

-Ken

**Comment by ridale** [comment]
I am seeing the same behavior, browser is chrome Version 56.0.2924.87 (64-bit) on ubuntu.

**Comment by jullrich** [comment]
fixed. Please open again if it is still happening . (ridale: the ip you show is invalid. But it should still not log you out. it should just to a "generic search" for that term.)
