### ISSUE TITLE
My report page graph not rendering

### ISSUE THREAD

**Issue by joshlinx** [jullrich/ISC-Bugs#19]
It seems the graph engine is not rendering. It always displays waiting for data....

![graph](https://cloud.githubusercontent.com/assets/26198849/24072972/cb40cce8-0bef-11e7-90e7-6c240c39ad82.PNG)

**Comment by oisteink** [comment]
This is what Chrome reports:
myreports.html:1 Refused to execute script from 'https://isc.sans.edu/js/myReportsGraph.html?date=' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I can't get it to load on any other browser either

**Comment by jullrich** [comment]
This should be fixed now. Thanks to oisteink for the additional info!
