### ISSUE TITLE
Cannot Change Primary E-Mail Addr

### ISSUE THREAD

**Issue by PaulDeStefano** [jullrich/ISC-Bugs#22]
I've logged in and even changed my password, but I cannot change my primary e-mail address.  Can someone help me?

84.100.141.xxx
Sat, 01 Jul 2017 06:09:04 +0000
0172a806aed5e76331ebb1cb74c57274ee5cc9c0

**Comment by jullrich** [comment]
please try again. make sure you first add your new  email address as a validated address. Then you can swap out email address. send a messages via isc.sans.edu/contact.html if you still have problems.

**Comment by da2x** [comment]
Please re-open. I also can’t change my email address. I’m told the password is incorrect, even thought the same password works when logging in to the service (copy-pasted).

**Comment by jullrich** [comment]
reopening and doing more debugging.

**Comment by da2x** [comment]
@jullrich, I suspect that it may be the [same encoding issue that I just fixed in DShield](https://github.com/DShield-ISC/dshield/pull/61) or at least related.

**Comment by jullrich** [comment]
i believe this has been fixed. please reopen if it still doesn't work.
