### ISSUE TITLE
Subscription Timing Off

### ISSUE THREAD

**Issue by robv-uwhqcr** [jullrich/ISC-Bugs#27]
Once again (recurring problem that is not fixed) my subscription "magically changed" from Daily Summary at 1200 UTC to whatever it's doing now (got a Summary a little while ago).  In the last few minutes I've tried resetting it all sorts of ways (e.g., unsubscribing and then resubscribing).  Nothing works.  It's maddening.  As I said last time, "it's not rocket science."

**Comment by jullrich** [comment]
The "Preferred Delivery Time for Daily E-mail" on the "My Account" page refers to the daily diary summaries. The Daily Summary E-Mails which summarize your reports are scheduled automatically. I will see about adding a feature to allow you to set a specific time. Note that it may take up to 60 minutes for the latest reports to be processed.

**Comment by jullrich** [comment]
made a change live to fix/clarify this. Added a field to select the preferred hour for the daily report summary.
