### ISSUE TITLE
Errors sending to report@dshield.org

### ISSUE THREAD

**Issue by b-morgan** [jullrich/ISC-Bugs#28]
I'm getting errors when sending to report@dshield.org. Normally, my firewall (IPFire 2.19 core 113) sends the email using sendEmail. The failures are reported back to my Windows 10 system via Outlook 2016. I forward the message back to report@dshield.org and they have been successful until this one.
The following are the messages I get in the failure email:

This is an automatically generated Delivery Status Notification.      

Delivery to the following recipients failed permanently:

   * report@dshield.org

Reason: Permanent Error

Reporting-MTA: dns; resqmta-po-03v.sys.comcast.net [96.114.154.162]
Received-From-MTA: dns; resomta-po-08v.sys.comcast.net [96.114.154.232]
Arrival-Date: Sun, 01 Oct 2017 16:20:45 +0000

Final-recipient: rfc822; report@dshield.org
Diagnostic-Code: smtp; 
Last-attempt-Date: Sun, 01 Oct 2017 16:20:45 +0000

Received: from resomta-po-08v.sys.comcast.net ([96.114.154.232])
	by resqmta-po-03v.sys.comcast.net with ESMTP
	id ygywdbkH8XHLpygyzdcUKd; Sun, 01 Oct 2017 16:20:45 +0000
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=comcast.net;
	s=q20161114; t=1506874845;
	bh=zvHP5dMIbxqw6/LEYmkP0neg5OoOz/h/ClEIh5OThlw=;
	h=Received:Received:From:To:Subject:Date:Message-ID:MIME-Version:
	 Content-Type;
	b=N8qwXPcvhfSxI4af5eMAAL/J7DkmjbPLMw0Y+M6lEnAZiH0goaFy2oojOaIeRx0f6
	 duKiXTJjn7feuFTz+XB1JTEaKiZTHLbisn7cVECYDIfy8woN7yxJa+5RBQu+qljEEf
	 PFvxf1on5PHfL00kNupztFzfvp/yaPtyyQDwUM97Zh2xMmleUNf7e13nlRhevrzBqR
	 6sWPzHj6X0SsBDSj33l3g9mdqnT18uTnvIWSGJdWATYdpCuT2gpDx50nSq6YqSOMYi
	 4c6r/H9QqoAtfn4YlNMLta5ynn1YeusSL6VHDskg3+i2HyCVMdPNa0iNFDULAFI/AM
	 alF7fE1XlCrqA==
Received: from BRADMORGAN5 ([73.95.48.135])
	by resomta-po-08v.sys.comcast.net with SMTP
	id ygyud6coBDlaOygyvdRYLp; Sun, 01 Oct 2017 16:20:44 +0000
From: "Brad Morgan" <brad-morgan@comcast.net>
To: <report@dshield.org>
References: <163358.896362723-sendEmail@bricknix>
In-Reply-To: <163358.896362723-sendEmail@bricknix>
Subject: FORMAT IPTABLES USERID 99553829 TZ -06:00 VERSION DShield Framework 2013-05-17 IPTABLES 2013-05-17
Date: Sun, 1 Oct 2017 10:20:40 -0600
Message-ID: <009d01d33ad1$3ad2b660$b0782320$@comcast.net>
MIME-Version: 1.0
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit
X-Mailer: Microsoft Outlook 16.0
thread-index: AQHEmAt7Oj8kEF3+WTXoo+rHheU4aaLscjeg
Content-Language: en-us
X-CMAE-Envelope: MS4wfFv0ks6G3AypuYeetGksuh/4AY16AE7YuXAYCuFrcaaKaEgQ29YFnA5024OATiZrZIvoWTxrNF+MfztnzEAeTKx8jAq5KScdZ4QqsiPcMXfeoq/nti2g
 mq4KhRJ0Zo6hoIjt/5nQg+P0AepwosaL4wsML1/Qg6qYPZhIVn6EuQeL

**Comment by jullrich** [comment]
is this still an issue? Our mail server has been working and accepting e-mail, so not sure why Comcast wouldn't forward the e-mail. The error message doesn't give me any hints. Please re-open if this is still a problem.
