### ISSUE TITLE
DShield Reports not being returned

### ISSUE THREAD

**Issue by mikep11** [jullrich/ISC-Bugs#30]
I am submitting my logs (and getting the receipt confirmation emails) but for the past few days I have been receiving empty reports.

Once I started submitting reports with the AUTHKEY (January 2), I started receiving reports to my submission email (not my account email). Starting on January 10 (except for January 12), I am getting "you did not submit any reports today" emails at my account email.  I did not make any changes on my end over the course of these days.

I would rather receive the emails at the account email, but some content would be nice too!

**Comment by jullrich** [comment]
I hope to have this fixed now. A parser problem caused some reports to be dropped.Please reopen if you still have this issue.

**Comment by mikep11** [comment]
No change - still received the "you did not submit any reports today" emails at my account email.

(Note: unable to reopen this issue by myself)

**Comment by jullrich** [comment]
can you please e-mail me your userid / email address ( jullrich /at/ sans.edu ).

**Comment by mikep11** [comment]
It is back to normal - reports are being sent to the submitting email.

Thank you for the assistance!
