### ISSUE TITLE
Allzeros for past 10 days

### ISSUE THREAD

**Issue by FireballDWF** [jullrich/ISC-Bugs#31]
Saw https://isc.sans.edu/webhoneypot/ is showing all zero's for past 10 days, leading me to wonder if it's a dead project.  Don't want to invest time in learning how to participate if it's a dead project.  But if it's alive, willing to.

**Comment by gebhard73** [comment]
If it's not dead it should be included in https://github.com/DShield-ISC/dshield IMHO ....

**Comment by jullrich** [comment]
not a dead project. but working on redoing the stats. We actually got quite a bit of logs that just need to be displayed right. Gebhard's comment is good as this is also part of the honeypot. (but bugs can be reported either way)

**Comment by jullrich** [comment]
I "fixed" that page for now. I had to remove two tables at the bottom (attach characterization) as that isn't working yet for the newer logs and more difficult to fix.
