### ISSUE TITLE
Podcast channel not updating on Google Play Music

### ISSUE THREAD

**Issue by bigben386** [jullrich/ISC-Bugs#37]
Hi,

The ISC podcast channel in GPM does not show any episodes after 2018-07-06
![image](https://user-images.githubusercontent.com/9749364/42830544-c1892616-89b9-11e8-923c-d67c7ff5460f.png)

**Comment by jullrich** [comment]
I think I fixed it. Google didn't like the way I specified the "Author" anymore. The feed now passes, but it may take a while for google to start publishing it again. Odd issue and looks like Google changed the specs they access.

**Comment by jullrich** [comment]
will leave this open until google actually publishes the recent podcasts.

**Comment by bigben386** [comment]
Awesome. Thank you for the fix. Hopefully I will have something to listen to on my commute tomorrow.

**Comment by bigben386** [comment]
Hi Johannes,
Your fix worked. Thank you so much. Really enjoy the podcast.
![image](https://user-images.githubusercontent.com/9749364/42954464-cdbcf18c-8b4a-11e8-8a24-ffc712a38a79.png)

**Comment by snowman386** [comment]
Seems this is broken again
![image](https://user-images.githubusercontent.com/12498653/44285192-5dc42400-a232-11e8-8070-0fced4f168d5.png)

**Comment by jullrich** [comment]
Sorry :( No idea why this keeps happening, other than may be an issue with Libsyn. I may have to move away from Libsyn for hosting. I will try to switch the RSS feed over to my own server. Please keep me in the loop on what you are seeing.
