### ISSUE TITLE
dShield reports not being recieved

### ISSUE THREAD

**Issue by jvedman** [jullrich/ISC-Bugs#39]
I have several clients sending dShield reporting from pfSense 2.4.3 boxes. I can see that the reports in my sent mail box, but I'm not receiving any responses after 9/17/2018, and my account/reports all show no reports after that date also.

Any thoughts?

**Comment by jullrich** [comment]
Could you please email me your userid so I can debug this from my end? (Jullrich@ sans . Edu)

**Comment by jvedman** [comment]
Sent through my work email with subject: dShield reporting issues

**Comment by jvedman** [comment]
And, I'm planning on updating the firewalls to 2.4.4, so if you want me to do that as a test, let me know.

**Comment by martinboller** [comment]
Having the same issue from an Iptables.pl client 
Subject: FORMAT IPTABLES USERID xxxxxxxxxx TZ +00:00 VERSION DShield Framework 2013-05-17 IPTABLES 2013-05-17 
Added a to address in .cnf and that is receiving mails. No data since 2018-12-30

**Comment by jullrich** [comment]
I looked at your account and our logs. I do not see any incoming emails after Dec. 30th based on my maillog. Are you sure the logs are going out? The last email I see arriving was from Dec 30 12:17:06, based on my mail server log (UTC)

**Comment by jullrich** [comment]
closing this for now. Let me know if you have any additional input.
