### ISSUE TITLE
Show reports on - Time Warp

### ISSUE THREAD

**Issue by gregkuhnert** [jullrich/ISC-Bugs#41]
The default date for the "Show reports on" field in myreports.html is a little unhelpful. Its not a 2019 date, not even 2018. January 2017 is not really useful. Can we get rid of the "time warp" please?

**Comment by jullrich** [comment]
can you send me a screenshot please? For me, the form displays today's date as the default. A screenshot may help reproduce this issue.

**Comment by gregkuhnert** [comment]
<img width="1003" alt="screenshot" src="https://user-images.githubusercontent.com/28210775/50575973-2d38fb80-0e5c-11e9-841d-0646157258cc.png">

**Comment by gregkuhnert** [comment]
And while we are at it - as reported in another ticket, no reports being parsed from me at the moment... I didn't want to share ID or email publicly - I was not sure how your security works to prevent forged submissions.

**Comment by jullrich** [comment]
the missing reports may be related. Can you e-mail me your userid (jullrich @ sans.edu) ? that will help. Or ping me via our slack channel (isc.sans.edu/slack/index.html )

**Comment by jullrich** [comment]
actually. I think I found your report. the 'Short reports' should now show Jan 1st 2019 if I found the right account. It was related to not receiving reports . Going to close this ticker  and will now work on the missing reports.
