### ISSUE TITLE
Reports not being received/parsed

### ISSUE THREAD

**Issue by gregkuhnert** [jullrich/ISC-Bugs#42]
My report submissions have been disabled for a while due to infrastructure upgrades. Its been back on for a while now, but the portal shows last report submission date as 2018-12-20 19:45:07

Anything wrong with the parsers?

**Comment by jullrich** [comment]
Can you let me know which method you use to submit logs?

**Comment by jullrich** [comment]
ok. I think I found your logs, and why they are not being recognized. The "From" address is wrong. I can change your account (or you can do it), or you can use the "AUTHKEY" as a method to authenticate (that is preferred) . You can find the key on the "myaccount" page. Add it to the e-mail subject like "AUTHKEY abadfalkdsfj" (unless you already do this. the email subject got truncated in the logs)

**Comment by jullrich** [comment]
closing this for now. Let me know if there are still issues receiving reports.
