### ISSUE TITLE
Inclusion of CVE #'s in API results?

### ISSUE THREAD

**Issue by ziesemer** [jullrich/ISC-Bugs#5]
Please compare https://isc.sans.edu/mspatchdays.html?viewday=2016-08-09 vs. https://isc.sans.edu/api/getmspatchday/2016-08-09 .  Is there a way to retrieve the CVE #'s associated with each Microsoft patch through the API, or can this please be added?

**Comment by jullrich** [comment]
done. please let me know if it isn't working for you.
