### ISSUE TITLE
What happened to rss feed SANS ISC SecNewsFeed

### ISSUE THREAD

**Issue by iii-iii** [jullrich/ISC-Bugs#54]
The feed "SANS ISC SecNewsFeed" with feed url http://isc.sans.edu/newssummary.xml has not been updated since 19th June 2019.

**Comment by jullrich** [comment]
The idea behind the SANS ISC News Feed was to have readers rank/rate news article. But this hardly ever happened so it became just another security news feed and we decided to remove it.
