### ISSUE TITLE
HDTracks Downloader asking for strange permission

### ISSUE THREAD

**Issue by xrscott** [jullrich/ISC-Bugs#55]
HDTracks downloader asking for permission to record screen.

![Screen Recording ](https://user-images.githubusercontent.com/57260567/68028965-7fb99300-fc8c-11e9-9f71-302ec0b6eb73.jpg)

https: // www.h dtracks.com /landing

https :// www.h dtracks.com /downloader/channels/v18/stable/HDtracksDownloader200057.dmg

**Comment by jullrich** [comment]
This does not appear to be an issue related to the isc.sans.edu site.
