### ISSUE TITLE
Dshield email reports say 'no reports submitted' but... My Reports status shows it's working

### ISSUE THREAD

**Issue by ktrue** [jullrich/ISC-Bugs#6]
Checking my My Reports status shows

Last Report:    Firewall reports: 2016-08-14 02:25:02
ssh/kippo reports: 2016-08-14 02:24:36
Today's Reports (Firewall+ssh):     71202 Lines
Current server time:    Sun, 14 Aug 2016 02:53:06 +0000 (day # 736555)

which says the report arrived.  Is there something wrong with the daily Dshield submission report?

**Comment by jullrich** [comment]
this has been fixed. please reopen if there are still problems.
