### ISSUE TITLE
Podcast RSS is too big for Alexa

### ISSUE THREAD

**Issue by rj-sec** [jullrich/ISC-Bugs#65]
For those of us with Amazon Alexa devices there's a feature called Flash Briefings where you simply say 'Alexa give me my flash briefing' and you get the news headlines etc. This is customisable so that various news sources can be added as long as they are already Alexa Skills. What I thought would be cool would be to listen to the latest Cyber Security news after the real news but I checked and was disappointed to find that there is no ISC StormCast skill available. I therefore followed the Amazon dev instructions to create an unoffical StormCast skill but got an error 'Feed content is too large. It turns out that Amazon limit RSS feed resonses to 1MB but currently https://isc.sans.edu/dailypodcast.xml returns approx 2.1MB. Would it be possible to create an alternative RSS feed which for example only provides the last 5-10 shows? This would def. be under 1MB. With this, either ISC could create an official ISC StormCast skill or I will be able to create the unoffical one so we can spread the StormCast word!

Thanks

Rich

**Comment by jullrich** [comment]
There is a special RSS feed for Alexa https://isc.sans.edu/alexa.rss . It only lists the last podcast. I believe there are already two Stormcast flash briefing skills available. 

For example: https://www.amazon.com/Ventz-Petkov-Stormcast-Internet-Center/dp/B01M679S9E/ref=sr_1_1?dchild=1&keywords=stormcast&qid=1608815012&s=digital-skills&sr=1-1

**Comment by rj-sec** [comment]
Thanks for responding. I had searched and the Alexa skills you mentioned and didn't come up for me. It seems they aren't available for Amazon.co.uk users because it has its own dedicated skills site. With that RSS though I can make one. Thanks!

**Comment by rj-sec** [comment]
Frustratingly I try to create the skill with this feed only to get a new error: "There was an error parsing the feed. Please ensure that the feed is valid JSON or RSS.". I've checked it with a couple of RSS feed validators (https://validator.w3.org/feed/ and https://castfeedvalidator.com/?url=https://isc.sans.edu/alexa.rss) and they are both saying it's invalid RSS which explains why Amazon is rejecting it. I wonder if the US based Alex skills were created before these validation checks were implemented by Amazon. Anyway, any chance we can try to fix the RSS?

**Comment by jullrich** [comment]
see if this JSON version works: https://isc.sans.edu/alexa.json

**Comment by rj-sec** [comment]
That works thanks. Hopefully people in the UK will be hearing more of you soon!
