### ISSUE TITLE
"Submitting e-mail address" not recognized as valid submission address

### ISSUE THREAD

**Issue by j7eich** [jullrich/ISC-Bugs#7]
I entered an e-mail address in my account's "submitting e-mail address" field that is different to my account e-mail address.
My psad installation uses the "submitting e-mail address" as FROM address when submitting firewall reports.
The submission confirmation e-mail (sent to my account e-mail address) states that "the e-mail address you used to submit this report from did not match the address we have on file".

**Comment by jullrich** [comment]
is this still happening? Please also consider using the "apikey" which should fix this problem. Let me know if the PSAD client needs an update. Leaving this issue open for now.
