### ISSUE TITLE
Password Reset issue

### ISSUE THREAD

**Issue by mricharf** [jullrich/ISC-Bugs#78]
I'm resetting my password, but when I get to the page to send an SMS to confirm the change (https://isc.sans.edu/phonereset.html), I click on "Select" next to my phone number and receive the following error:

Sorry, the page you where looking for could not be displayed at this time.

Select target: https://isc.sans.edu/phonereset2.html
id=<empty>
code=<redacted>
email=<redacted>

**Comment by jullrich** [comment]
I reworked this page, and think it is working now. (at least based on my own testing)
