### ISSUE TITLE
Font COlor

### ISSUE THREAD

**Issue by rickhellewell** [jullrich/ISC-Bugs#79]
I don't understand why almost all redesigns have a gray text on white background. Not everyone is under 30 here, and for these old eyes, the reduced contrast between text color and background makes everything harder to read.

But, I'm probably doing a 'Don Quioxte" .... all the 'cool kids' think gray text on white background shows how cool they are.

(Insert "get off my lawn" here, if needed)

**Comment by sebenste** [comment]
I just came here to post this. Absolutely. Grey on white absolutely stinks for my eyes. I can barely read it on the latest version of Chrome on Windows 10/64-bit, 1080p screen, via a laptop.

**Comment by jullrich** [comment]
experimenting with a different darker grey. (not closing this yet)
