### ISSUE TITLE
Cannot change email or password

### ISSUE THREAD

**Issue by theshoehorn** [jullrich/ISC-Bugs#8]
When trying to change the email address associated with my account, it tells me to enter a valid "current" password. The password being entered is indeed correct. 

The same issue is seen when trying to change the password.

**Comment by jkljklhhjkjlhghjgjhghjg** [comment]
I've figured it out.  Change back report email to match the original.  Then change email with the current password entered. Then go and change the report email.  Of course, there's no initial warning to enter current password, that and the email bug makes for an interesting headache.

**Comment by jullrich** [comment]
ok. I totally redid this part. Thre were a couple of different issues. Most notably, if another account already existed with the new e-mail address, then you got an error. I now split this into two parts: First you can "add" e-mail addresses to your account. This will validate the e-mail address (you need to acknowledge a code that is sent to you) and then you can swap your "primary e-mail" address. I hope this all helps. Will close this issue for now.
